#!/usr/bin/env bun
import { resolve } from "node:path";

const root = resolve(import.meta.dir, "..");
const entry = resolve(root, "src/lib/sandbox/protocol/preamble/zod-entry.ts");
const outFile = resolve(
	root,
	"src/lib/sandbox/protocol/preamble/zod.bundle.ts",
);

const result = await Bun.build({
	entrypoints: [entry],
	target: "browser",
	format: "iife",
	minify: true,
});

if (!result.success) {
	for (const log of result.logs) console.error(log);
	process.exit(1);
}

const [output] = result.outputs;
if (!output) throw new Error("no build output");
const source = await output.text();

const ts = `// Generated by scripts/build-preamble.ts. Do not edit by hand.
// Run \`bun run build:preamble\` to regenerate.
export const zodBundleSource = ${JSON.stringify(source)};
export const zodBundleBytes = ${source.length};
`;

await Bun.write(outFile, ts);
console.log(`wrote ${outFile} (${source.length} bytes of zod)`);
